"""empty message

Revision ID: 4fdddd0c70a8
Revises: 11ea77decb90
Create Date: 2016-10-19 13:20:11.515853

"""

# revision identifiers, used by Alembic.
revision = '4fdddd0c70a8'
down_revision = '11ea77decb90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
